// src/services/invoice.service.js
const { Invoice, InvoiceLineItem, Customer, AuditLog } = require('../models');
const { Op } = require('sequelize');
const { generateInvoiceNumber } = require('./../utils/generateInvoice');
// src/services/invoice.service.js - createInvoice function

const createInvoice = async (userId, invoiceData) => {
  try {
    const {
      invoiceNumber: providedInvoiceNumber,
      customerPhone,
      customerName,
      customerId,
      dueDate,
      subTotal,
      paymentMethod,
      paymentLink,
      notes,
    } = invoiceData;

    const VAT_RATE = 0.075;
    const vatAmount = parseFloat((subTotal * VAT_RATE).toFixed(2));
    const totalAmount = parseFloat((subTotal + vatAmount).toFixed(2));

    const issueDate = new Date().toISOString().split('T')[0];
    const resolvedDueDate = dueDate
      ? new Date(dueDate).toISOString().split('T')[0]
      : issueDate;

    let resolvedCustomerId = customerId;
    let resolvedCustomer = null;

    // If no customerId but customer details provided, find or create
    if (!customerId && (customerPhone || customerName)) {
      let customer = null;

      // Try to find by phone first
      if (customerPhone) {
        customer = await Customer.findOne({
          where: { userId, phone: customerPhone },
        });
      }

      // If not found, create new customer
      if (!customer) {
        customer = await Customer.create({
          userId,
          name: customerName || 'One-time Customer',
          phone: customerPhone,
          type: 'individual',
        });
      }

      resolvedCustomerId = customer.id;
      resolvedCustomer = customer;
    }

    // Auto-generate invoice number if not provided
    let invoiceNumber = providedInvoiceNumber;
    if (!invoiceNumber) {
      invoiceNumber = await generateInvoiceNumber(userId);
    }

    // Check for duplicate
    const existingInvoice = await Invoice.findOne({
      where: { userId, invoiceNumber },
    });

    if (existingInvoice) {
      const error = new Error('Invoice number already exists for this user');
      error.statusCode = 400;
      throw error;
    }

    const invoice = await Invoice.create({
      userId,
      customerId: resolvedCustomerId,
      customerName: customerName || resolvedCustomer?.name,
      customerPhone: customerPhone || resolvedCustomer?.phone,
      customerEmail: resolvedCustomer?.email,
      invoiceNumber,
      issueDate,
      dueDate,
      subTotal,
      vatAmount,
      totalAmount,
      paymentMethod,
      paymentLink,
      notes,
      firsRetryCount: 0,
      firsStatus: 'pending',
    });

    // Log to audit
    await AuditLog.create({
      userId,
      entityType: 'invoice',
      entityId: invoice.id,
      action: 'create',
      status: 'success',
      metadata: {
        invoiceNumber: invoice.invoiceNumber,
        total: invoice.totalAmount,
        autoGenerated: !providedInvoiceNumber,
        customerCreated: !customerId && (customerPhone || customerName),
      },
    });

    return invoice;
  } catch (error) {
    throw error;
  }
};

const listInvoices = async (userId, options = {}) => {
  try {
    const { page = 1, limit = 10, status, paymentStatus } = options;
    const offset = (page - 1) * limit;

    const where = { userId };

    if (status) {
      where.firsStatus = status;
    }

    if (paymentStatus) {
      where.paymentStatus = paymentStatus;
    }

    const { count, rows } = await Invoice.findAndCountAll({
      where,
      include: ['customer'],
      order: [['createdAt', 'DESC']],
      limit,
      offset,
    });

    return {
      invoices: rows,
      pagination: {
        total: count,
        page,
        limit,
        pages: Math.ceil(count / limit),
      },
    };
  } catch (error) {
    throw error;
  }
};

const getInvoiceById = async (userId, invoiceId) => {
  try {
    const invoice = await Invoice.findOne({
      where: { id: invoiceId, userId },
      include: ['customer', 'lineItems', 'auditTrail'],
    });

    if (!invoice) {
      const error = new Error('Invoice not found');
      error.statusCode = 404;
      throw error;
    }

    return invoice;
  } catch (error) {
    throw error;
  }
};

const updateInvoice = async (userId, invoiceId, updates) => {
  try {
    const restrictedFields = [
      'customerName',
      'customerPhone',
      'customerEmail',
      'customerId',
    ];
    const attemptedRestricted = restrictedFields.filter(
      (field) => field in updates,
    );

    if (attemptedRestricted.length > 0) {
      const error = new Error(
        `Cannot update customer details: ${attemptedRestricted.join(', ')}. Customer info is locked after invoice creation.`,
      );
      error.statusCode = 400;
      throw error;
    }

    const invoice = await Invoice.findOne({
      where: { id: invoiceId, userId },
    });

    if (!invoice) {
      const error = new Error('Invoice not found');
      error.statusCode = 404;
      throw error;
    }

    // Don't allow updates if already validated with FIRS
    if (invoice.firsStatus === 'validated') {
      const error = new Error(
        'Cannot update invoice that has been validated by FIRS',
      );
      error.statusCode = 400;
      throw error;
    }

    const before = invoice.toJSON();
    await invoice.update(updates);
    const after = invoice.toJSON();

    // Track changes
    const changes = {};
    Object.keys(updates).forEach((key) => {
      if (before[key] !== after[key]) {
        changes[key] = { before: before[key], after: after[key] };
      }
    });

    // Log to audit
    await AuditLog.create({
      userId,
      entityType: 'invoice',
      entityId: invoiceId,
      action: 'update',
      changes,
      status: 'success',
      metadata: {
        restrictedFieldsAttempted:
          attemptedRestricted.length > 0 ? attemptedRestricted : null,
      },
    });

    return invoice;
  } catch (error) {
    throw error;
  }
};

const deleteInvoice = async (userId, invoiceId) => {
  try {
    const invoice = await Invoice.findOne({
      where: { id: invoiceId, userId },
    });

    if (!invoice) {
      const error = new Error('Invoice not found');
      error.statusCode = 404;
      throw error;
    }

    await invoice.destroy();

    // Log to audit
    await AuditLog.create({
      userId,
      entityType: 'invoice',
      entityId: invoiceId,
      action: 'delete',
      status: 'success',
    });
  } catch (error) {
    throw error;
  }
};

const submitToFirs = async (userId, invoiceId) => {
  try {
    const invoice = await Invoice.findOne({
      where: { id: invoiceId, userId },
    });

    if (!invoice) {
      const error = new Error('Invoice not found');
      error.statusCode = 404;
      throw error;
    }

    // Update attempt tracking
    invoice.lastFirsAttempt = new Date();
    invoice.firsRetryCount += 1;
    invoice.firsStatus = 'submitted';
    await invoice.save();

    // TODO: Call actual FIRS API here
    // const firsResponse = await callFirsApi(invoice);
    // invoice.firsIRN = firsResponse.irn;
    // invoice.qrCodeUrl = firsResponse.qrCode;
    // invoice.firsStatus = 'validated';
    // await invoice.save();

    // Log to audit
    await AuditLog.create({
      userId,
      entityType: 'invoice',
      entityId: invoiceId,
      action: 'firs_submit',
      status: 'success',
      metadata: {
        retryCount: invoice.firsRetryCount,
      },
    });

    return invoice;
  } catch (error) {
    // Log failed attempt
    await AuditLog.create({
      userId,
      entityType: 'invoice',
      entityId: invoiceId,
      action: 'firs_submit',
      status: 'failed',
      errorMessage: error.message,
    });

    throw error;
  }
};

const recordPayment = async (userId, invoiceId, amount, method) => {
  try {
    const invoice = await Invoice.findOne({
      where: { id: invoiceId, userId },
    });

    if (!invoice) {
      const error = new Error('Invoice not found');
      error.statusCode = 404;
      throw error;
    }

    if (amount <= 0) {
      const error = new Error('Payment amount must be greater than 0');
      error.statusCode = 400;
      throw error;
    }

    invoice.paymentStatus = 'paid';
    invoice.paidAt = new Date();
    await invoice.save();

    // Log to audit
    await AuditLog.create({
      userId,
      entityType: 'payment',
      entityId: invoiceId,
      action: 'payment_received',
      status: 'success',
      metadata: {
        amount,
        method,
        timestamp: new Date(),
      },
    });

    return invoice;
  } catch (error) {
    throw error;
  }
};

module.exports = {
  createInvoice,
  listInvoices,
  getInvoiceById,
  updateInvoice,
  deleteInvoice,
  submitToFirs,
  recordPayment,
};
